# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dumpy/programmin/projects/realmode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dumpy/programmin/projects/realmode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dumpy/programmin/projects/realmode/CMakeFiles /home/dumpy/programmin/projects/realmode//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dumpy/programmin/projects/realmode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named realmode

# Build rule for target.
realmode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 realmode
.PHONY : realmode

# fast build rule for target.
realmode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/build
.PHONY : realmode/fast

#=============================================================================
# Target rules for targets named realmode_dump

# Build rule for target.
realmode_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 realmode_dump
.PHONY : realmode_dump

# fast build rule for target.
realmode_dump/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode_dump.dir/build.make CMakeFiles/realmode_dump.dir/build
.PHONY : realmode_dump/fast

asm/call_int.o: asm/call_int.cc.o
.PHONY : asm/call_int.o

# target to build an object file
asm/call_int.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/call_int.cc.o
.PHONY : asm/call_int.cc.o

asm/call_int.i: asm/call_int.cc.i
.PHONY : asm/call_int.i

# target to preprocess a source file
asm/call_int.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/call_int.cc.i
.PHONY : asm/call_int.cc.i

asm/call_int.s: asm/call_int.cc.s
.PHONY : asm/call_int.s

# target to generate assembly for a file
asm/call_int.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/call_int.cc.s
.PHONY : asm/call_int.cc.s

asm/halt.o: asm/halt.cc.o
.PHONY : asm/halt.o

# target to build an object file
asm/halt.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/halt.cc.o
.PHONY : asm/halt.cc.o

asm/halt.i: asm/halt.cc.i
.PHONY : asm/halt.i

# target to preprocess a source file
asm/halt.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/halt.cc.i
.PHONY : asm/halt.cc.i

asm/halt.s: asm/halt.cc.s
.PHONY : asm/halt.s

# target to generate assembly for a file
asm/halt.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/asm/halt.cc.s
.PHONY : asm/halt.cc.s

bios/int10h.o: bios/int10h.cc.o
.PHONY : bios/int10h.o

# target to build an object file
bios/int10h.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int10h.cc.o
.PHONY : bios/int10h.cc.o

bios/int10h.i: bios/int10h.cc.i
.PHONY : bios/int10h.i

# target to preprocess a source file
bios/int10h.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int10h.cc.i
.PHONY : bios/int10h.cc.i

bios/int10h.s: bios/int10h.cc.s
.PHONY : bios/int10h.s

# target to generate assembly for a file
bios/int10h.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int10h.cc.s
.PHONY : bios/int10h.cc.s

bios/int13h.o: bios/int13h.cc.o
.PHONY : bios/int13h.o

# target to build an object file
bios/int13h.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int13h.cc.o
.PHONY : bios/int13h.cc.o

bios/int13h.i: bios/int13h.cc.i
.PHONY : bios/int13h.i

# target to preprocess a source file
bios/int13h.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int13h.cc.i
.PHONY : bios/int13h.cc.i

bios/int13h.s: bios/int13h.cc.s
.PHONY : bios/int13h.s

# target to generate assembly for a file
bios/int13h.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int13h.cc.s
.PHONY : bios/int13h.cc.s

bios/int16h.o: bios/int16h.cc.o
.PHONY : bios/int16h.o

# target to build an object file
bios/int16h.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int16h.cc.o
.PHONY : bios/int16h.cc.o

bios/int16h.i: bios/int16h.cc.i
.PHONY : bios/int16h.i

# target to preprocess a source file
bios/int16h.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int16h.cc.i
.PHONY : bios/int16h.cc.i

bios/int16h.s: bios/int16h.cc.s
.PHONY : bios/int16h.s

# target to generate assembly for a file
bios/int16h.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/bios/int16h.cc.s
.PHONY : bios/int16h.cc.s

disk/address.o: disk/address.cc.o
.PHONY : disk/address.o

# target to build an object file
disk/address.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/disk/address.cc.o
.PHONY : disk/address.cc.o

disk/address.i: disk/address.cc.i
.PHONY : disk/address.i

# target to preprocess a source file
disk/address.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/disk/address.cc.i
.PHONY : disk/address.cc.i

disk/address.s: disk/address.cc.s
.PHONY : disk/address.s

# target to generate assembly for a file
disk/address.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/disk/address.cc.s
.PHONY : disk/address.cc.s

terminal/terminal.o: terminal/terminal.cc.o
.PHONY : terminal/terminal.o

# target to build an object file
terminal/terminal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/terminal/terminal.cc.o
.PHONY : terminal/terminal.cc.o

terminal/terminal.i: terminal/terminal.cc.i
.PHONY : terminal/terminal.i

# target to preprocess a source file
terminal/terminal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/terminal/terminal.cc.i
.PHONY : terminal/terminal.cc.i

terminal/terminal.s: terminal/terminal.cc.s
.PHONY : terminal/terminal.s

# target to generate assembly for a file
terminal/terminal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/terminal/terminal.cc.s
.PHONY : terminal/terminal.cc.s

util/farptr.o: util/farptr.cc.o
.PHONY : util/farptr.o

# target to build an object file
util/farptr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/util/farptr.cc.o
.PHONY : util/farptr.cc.o

util/farptr.i: util/farptr.cc.i
.PHONY : util/farptr.i

# target to preprocess a source file
util/farptr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/util/farptr.cc.i
.PHONY : util/farptr.cc.i

util/farptr.s: util/farptr.cc.s
.PHONY : util/farptr.s

# target to generate assembly for a file
util/farptr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realmode.dir/build.make CMakeFiles/realmode.dir/util/farptr.cc.s
.PHONY : util/farptr.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... realmode_dump"
	@echo "... realmode"
	@echo "... asm/call_int.o"
	@echo "... asm/call_int.i"
	@echo "... asm/call_int.s"
	@echo "... asm/halt.o"
	@echo "... asm/halt.i"
	@echo "... asm/halt.s"
	@echo "... bios/int10h.o"
	@echo "... bios/int10h.i"
	@echo "... bios/int10h.s"
	@echo "... bios/int13h.o"
	@echo "... bios/int13h.i"
	@echo "... bios/int13h.s"
	@echo "... bios/int16h.o"
	@echo "... bios/int16h.i"
	@echo "... bios/int16h.s"
	@echo "... disk/address.o"
	@echo "... disk/address.i"
	@echo "... disk/address.s"
	@echo "... terminal/terminal.o"
	@echo "... terminal/terminal.i"
	@echo "... terminal/terminal.s"
	@echo "... util/farptr.o"
	@echo "... util/farptr.i"
	@echo "... util/farptr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

